### ISSUE TITLE
ecto.create gives argument error

### ISSUE THREAD

**Issue by kosantosbik** [oeb25/chess#2]
mix ecto.create gives the following error :

17:24:53.571 [error] GenServer #PID<0.208.0> terminating
** (ArgumentError) argument error
    :erlang.element(1, :error)
    (postgrex) lib/postgrex/utils.ex:67: anonymous fn/1 in Postgrex.Utils.parse_version/1
    (elixir) lib/enum.ex:1294: Enum."-map/2-lists^map/1-0-"/2
    (elixir) lib/enum.ex:1294: Enum."-map/2-lists^map/1-0-"/2
    (postgrex) lib/postgrex/utils.ex:67: Postgrex.Utils.parse_version/1
    (postgrex) lib/postgrex/protocol.ex:639: Postgrex.Protocol.bootstrap_send/4
    (postgrex) lib/postgrex/protocol.ex:475: Postgrex.Protocol.handshake/2
    (db_connection) lib/db_connection/connection.ex:134: DBConnection.Connection.connect/2
    (connection) lib/connection.ex:622: Connection.enter_connect/5
    (stdlib) proc_lib.erl:249: :proc_lib.init_p_do_apply/3
Last message: nil
State: Postgrex.Protocol
** (Mix) The database for Chess.Repo couldn't be created: an exception was raised:
    ** (ArgumentError) argument error
        :erlang.element(1, :error)
        (postgrex) lib/postgrex/utils.ex:67: anonymous fn/1 in Postgrex.Utils.parse_version/1
        (elixir) lib/enum.ex:1294: Enum."-map/2-lists^map/1-0-"/2
        (elixir) lib/enum.ex:1294: Enum."-map/2-lists^map/1-0-"/2
        (postgrex) lib/postgrex/utils.ex:67: Postgrex.Utils.parse_version/1
        (postgrex) lib/postgrex/protocol.ex:639: Postgrex.Protocol.bootstrap_send/4
        (postgrex) lib/postgrex/protocol.ex:475: Postgrex.Protocol.handshake/2
        (db_connection) lib/db_connection/connection.ex:134: DBConnection.Connection.connect/2
        (connection) lib/connection.ex:622: Connection.enter_connect/5
        (stdlib) proc_lib.erl:249: :proc_lib.init_p_do_apply/3

**Comment by kosantosbik** [comment]
I am new at elixir and somehow i couldn't locate the error and fix it :(
